server:
  port: 8085

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/newdemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  resources:
      static-locations: classpath:/templates

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
  timeout: 5000

#spring-session
#session:
#  store-type: redis
#  timeout: PT30M

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


#showSql
logging:
  level:
    com:
      example:
        demo:
          mapper : debug